spring:
  datasource:
    url: jdbc:h2:mem:opsany_preview;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    listener:
      simple:
        auto-startup: false

app:
  messaging:
    consumer-enabled: false
    fallback-on-publish-failure: true
